export const DEFAULT_PERMISSIONS = [
  { key: "leads.view", group: "leads", description: "View leads" },
  { key: "leads.create", group: "leads", description: "Create leads" },
  { key: "leads.edit", group: "leads", description: "Edit leads" },
  { key: "leads.delete", group: "leads", description: "Delete leads" },
  { key: "customers.view", group: "customers", description: "View customers" },
  { key: "customers.create", group: "customers", description: "Create customers" },
  { key: "customers.edit", group: "customers", description: "Edit customers" },
  { key: "quotes.view", group: "quotes", description: "View quotes" },
  { key: "quotes.create", group: "quotes", description: "Create quotes" },
  { key: "quotes.edit", group: "quotes", description: "Edit quotes" },
  { key: "quotes.delete", group: "quotes", description: "Delete quotes" },
  { key: "users.view", group: "users", description: "View users" },
  { key: "users.create", group: "users", description: "Create users" },
  { key: "users.edit", group: "users", description: "Edit users" },
  { key: "users.delete", group: "users", description: "Delete users" },
  { key: "users.manage", group: "users", description: "Manage users and invitations" },
  { key: "roles.manage", group: "users", description: "Manage roles and permissions" },
  { key: "settings.manage", group: "settings", description: "Manage organization settings" },
  { key: "pipeline.manage", group: "leads", description: "Manage pipeline stages" },
  { key: "estimate_rules.manage", group: "quotes", description: "Manage estimate rules" },
  { key: "builders.view", group: "builders", description: "View builders" },
  { key: "builders.edit", group: "builders", description: "Edit builders" },
  { key: "payroll.view", group: "payroll", description: "View payroll" },
  { key: "payroll.manage", group: "payroll", description: "Manage payroll" },
  { key: "projects.view", group: "projects", description: "View projects" },
  { key: "reports.view", group: "reports", description: "View reports / marketing" },
  { key: "contracts.view", group: "financial", description: "View financial / contracts" },
  { key: "visits.view", group: "operations", description: "View schedule / visits" },
] as const;

export type PermissionKey = (typeof DEFAULT_PERMISSIONS)[number]["key"];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, PermissionKey[]> = {
  admin: DEFAULT_PERMISSIONS.map((p) => p.key),
  sales_rep: [
    "leads.view",
    "leads.create",
    "leads.edit",
    "customers.view",
    "customers.create",
    "customers.edit",
    "quotes.view",
    "quotes.create",
    "quotes.edit",
    "builders.view",
  ],
  project_manager: [
    "leads.view",
    "customers.view",
    "customers.edit",
    "quotes.view",
    "quotes.edit",
    "projects.view",
    "payroll.view",
    "builders.view",
  ],
  support: ["leads.view", "customers.view", "quotes.view"],
};

/** Senior Floors kanban v9 stage set */
export const DEFAULT_PIPELINE_STAGES = [
  { name: "New Lead", slug: "new_lead", order: 1, color: "#3498db", isClosed: false },
  { name: "Meeting Scheduled", slug: "meeting_scheduled", order: 2, color: "#90EE90", isClosed: false },
  { name: "Quote Sent", slug: "quote_sent", order: 3, color: "#9b59b6", isClosed: false },
  { name: "Follow Up", slug: "follow_up_1", order: 4, color: "#F1C40F", isClosed: false },
  { name: "Stand By", slug: "stand_by", order: 5, color: "#f39c12", isClosed: false },
  { name: "Won", slug: "won", order: 6, color: "#27ae60", isClosed: true },
  { name: "Lost", slug: "lost", order: 7, color: "#c0392b", isClosed: true },
];

export const DEFAULT_ESTIMATE_RULES = [
  {
    flooringType: "hardwood",
    wastePercent: 10,
    materialMarkup: 30,
    laborMarkup: 40,
    defaultPricePerSqft: 8.5,
    defaultLaborPerSqft: 3.5,
  },
  {
    flooringType: "lvp",
    wastePercent: 8,
    materialMarkup: 35,
    laborMarkup: 40,
    defaultPricePerSqft: 4.25,
    defaultLaborPerSqft: 2.75,
  },
  {
    flooringType: "laminate",
    wastePercent: 8,
    materialMarkup: 35,
    laborMarkup: 35,
    defaultPricePerSqft: 3.5,
    defaultLaborPerSqft: 2.5,
  },
  {
    flooringType: "tile",
    wastePercent: 12,
    materialMarkup: 40,
    laborMarkup: 45,
    defaultPricePerSqft: 5.5,
    defaultLaborPerSqft: 6.0,
  },
  {
    flooringType: "carpet",
    wastePercent: 10,
    materialMarkup: 30,
    laborMarkup: 35,
    defaultPricePerSqft: 2.75,
    defaultLaborPerSqft: 1.5,
  },
];
