/**
 * SF-compatible multi-tenant CRM APIs for System SaaS.
 * Modules: Dashboard, Leads, Quotes, Invoice, Cadastro, Builders, Pricing, Payroll, Users.
 */
import { Router } from "express";
import { dashboardLeadsRouter } from "./routes/dashboard-leads.js";
import { dashboardOverviewRouter } from "./routes/dashboard-overview.js";
import { customersQuotesRouter } from "./routes/customers-quotes.js";
import { invoicesCrmRouter } from "./routes/invoices.js";
import { buildersPricingRouter } from "./routes/builders-pricing.js";
import { cadastroPayrollUsersRouter } from "./routes/cadastro-payroll-users.js";
import { constructionPayrollRouter } from "./routes/construction-payroll.js";
import { brandingRouter } from "./routes/branding.js";
import { supportRouter } from "./routes/support.js";
import { pushRouter } from "./routes/push.js";
import { scheduleJobsRouter } from "./routes/schedule-jobs.js";
import { financeRouter } from "./routes/finance.js";
import { campoPontoRouter } from "./routes/campo-ponto.js";
import { campoJobsRouter } from "./routes/campo-jobs.js";
import { campoHorasRouter } from "./routes/campo-horas.js";
import { campoFolhaRouter } from "./routes/campo-folha.js";
import { campoDiaRouter } from "./routes/campo-dia.js";
import { folhaAdminRouter } from "./routes/folha-admin.js";
import { jobReportsRouter } from "./routes/job-reports.js";
import { jobQuotesRouter } from "./routes/job-quotes.js";
import { jobInvoicesRouter } from "./routes/job-invoices.js";
import { jobFieldSummaryRouter } from "./routes/job-field-summary.js";
import { jobFieldExtrasRouter } from "./routes/job-field-extras.js";
import { chatRouter } from "./routes/chat.js";
import { settingsOrganizationRouter } from "./routes/settings-organization.js";
import { settingsQuotesRouter } from "./routes/settings-quotes.js";
import { settingsLeadMessagesRouter } from "./routes/settings-lead-messages.js";
import { settingsLeadAutomationsRouter } from "./routes/settings-lead-automations.js";
import { settingsScheduleRouter } from "./routes/settings-schedule.js";
import { settingsJobsRouter } from "./routes/settings-jobs.js";
import { settingsCatalogRouter } from "./routes/settings-catalog.js";
import { reportsHubRouter } from "./routes/reports-hub.js";

export const crmApiRouter = Router();

crmApiRouter.use(brandingRouter);
crmApiRouter.use(settingsOrganizationRouter);
crmApiRouter.use(settingsQuotesRouter);
crmApiRouter.use(settingsLeadMessagesRouter);
crmApiRouter.use(settingsLeadAutomationsRouter);
crmApiRouter.use(settingsScheduleRouter);
crmApiRouter.use(settingsJobsRouter);
crmApiRouter.use(settingsCatalogRouter);
crmApiRouter.use(supportRouter);
crmApiRouter.use(pushRouter);
crmApiRouter.use(scheduleJobsRouter);
crmApiRouter.use(financeRouter);
crmApiRouter.use(dashboardOverviewRouter);
crmApiRouter.use(dashboardLeadsRouter);
crmApiRouter.use(invoicesCrmRouter);
crmApiRouter.use(customersQuotesRouter);
crmApiRouter.use(buildersPricingRouter);
crmApiRouter.use(constructionPayrollRouter);
crmApiRouter.use(cadastroPayrollUsersRouter);
crmApiRouter.use(campoPontoRouter);
crmApiRouter.use(campoJobsRouter);
crmApiRouter.use(campoHorasRouter);
crmApiRouter.use(campoFolhaRouter);
crmApiRouter.use(campoDiaRouter);
crmApiRouter.use(folhaAdminRouter);
crmApiRouter.use(jobReportsRouter);
crmApiRouter.use(jobQuotesRouter);
crmApiRouter.use(jobInvoicesRouter);
crmApiRouter.use(jobFieldSummaryRouter);
crmApiRouter.use(jobFieldExtrasRouter);
crmApiRouter.use(chatRouter);
crmApiRouter.use(reportsHubRouter);
